sonar.projectKey=carloseduardob_prova01-unit-test-CarlosEduardo
sonar.organization=carloseduardob
sonar.projectName=Jest Integration Tests
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8